This resource offers a total of 295 NumPy Basic problems for practice. It includes 59 main exercises, each accompanied by solutions, detailed explanations, and four related problems.

In [1]:
import numpy as np

1. Get the numpy version and Build Info

In [3]:
print(np.__version__)
print(np.show_config())

2.1.3
Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/g6/rgtlsw6n123b0gt5483s5_cm0000gn/T/build-en

2. Help for NumPy Add Function


In [4]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

3. Test None are Zero

Write a NumPy program to test whether none of the elements of a given array are zero. 

In [7]:
X = np.array([1,2,3,4])
print(f"The Orginial Array:",X)
print(f"Testing if non of element in {X} is :", np.all(X))

X = np.array([0, 1, 2, 3])
print(f"The Orginial Array:",X)
print(f"Testing if non of element in {X} is :", np.all(X))

The Orginial Array: [1 2 3 4]
Testing if non of element in [1 2 3 4] is : True
The Orginial Array: [0 1 2 3]
Testing if non of element in [0 1 2 3] is : False


4. Test Any Non-Zero

Write a NumPy program to test if any of the elements of a given array are non-zero. 

In [9]:
X = np.array([1,2,3,4])
print(f"The Orginial Array:",X)
print(f"Testing if non of element in {X} is :", np.any(X))

X = np.array([0, 1, 2, 3])
print(f"The Orginial Array:",X)
print(f"Testing if non of element in {X} is :", np.any(X))

The Orginial Array: [1 2 3 4]
Testing if non of element in [1 2 3 4] is : True
The Orginial Array: [0 1 2 3]
Testing if non of element in [0 1 2 3] is : True


5. Test Finiteness of Elements

Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a number).



In [11]:
arr = np.array([1.0, 0.0, np.nan, np.inf, -np.inf])
print(f"For the Array \n{arr}\n , the possibility of infiniteness is {np.isfinite(arr)}")


arr = np.array([0, 1, 2, 3])
print(f"For the Array \n{arr}\n , the possibility of infiniteness is {np.isfinite(arr)}")



For the Array 
[  1.   0.  nan  inf -inf]
 , the possibility of infiniteness is [ True  True False False False]
For the Array 
[0 1 2 3]
 , the possibility of infiniteness is [ True  True  True  True]


6. Test for Infinity

Write a NumPy program to test elements-wise for positive or negative infinity. 

In [12]:
arr = np.array([1.0, 0.0, np.nan, np.inf, -np.inf])
print(f"For the Array \n{arr}\n , the possibility of infiniteness is {np.isinf(arr)}")


arr = np.array([0, 1, 2, 3])
print(f"For the Array \n{arr}\n , the possibility of infiniteness is {np.isinf(arr)}")


For the Array 
[  1.   0.  nan  inf -inf]
 , the possibility of infiniteness is [False False False  True  True]
For the Array 
[0 1 2 3]
 , the possibility of infiniteness is [False False False False]


7. Test for NaN

Write a NumPy program to test element-wise for NaN of a given array.

In [13]:
arr = np.array([1.0, 0.0, np.nan, 0, -9])
print(f"For the Array \n{arr}\n , the possibility of infiniteness is {np.isnan(arr)}")


arr = np.array([0, 1, 2, 3])
print(f"For the Array \n{arr}\n , the possibility of infiniteness is {np.isnan(arr)}")


For the Array 
[ 1.  0. nan  0. -9.]
 , the possibility of infiniteness is [False False  True False False]
For the Array 
[0 1 2 3]
 , the possibility of infiniteness is [False False False False]


8. Test for Complex/Real/Scalar

Write a NumPy program to test element-wise for complex numbers, real numbers in a given array. Also test if a given number is of a scalar type or not. 

In [14]:
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print(f"Orginial Array = {a}")
print("Checking for complex number:")
print(np.iscomplex(a))
print("Checking for real number:")
print(np.isreal(a))
print("Checking for scalar type:")
print(np.isscalar(3.1))

   

Orginial Array = [1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Checking for complex number:
[ True False False False False  True]
Checking for real number:
[False  True  True  True  True False]
Checking for scalar type:
True


9. Test Element-Wise Tolerance Equality

Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [15]:
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
# Checking if the arrays with NaN (Not a Number) values are equal while treating NaN as equal
print(np.allclose([1.0, np.nan], [1.0, np.nan]))

# Checking if the arrays with NaN (Not a Number) values are equal considering NaN values as equal
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True)) 

False
True
False
False
True


10. Element-Wise Comparison (Greater/Less)

Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [16]:
x = np.array([3, 5])
y = np.array([2, 5])
print(f"Is {x} is greater than {y}: {np.greater(x,y)}")
print(f"Is {x} is greater than or equal {y}: {np.greater_equal(x,y)}")
print(f"Is {x} is less than {y}: {np.less(x,y)}")
print(f"Is {x} is less than or equal {y}: {np.less_equal(x,y)}")


Is [3 5] is greater than [2 5]: [ True False]
Is [3 5] is greater than or equal [2 5]: [ True  True]
Is [3 5] is less than [2 5]: [False False]
Is [3 5] is less than or equal [2 5]: [False  True]
